// GERADO pelo compositor do catálogo (Salvar no repo). NÃO editar à mão.
//
// Fonte das telas: a SPEC (JSON). O arquivo é função pura do estado do
// compositor — ver docs/ADR-001.
//
// ignore_for_file: prefer_single_quotes

const Map<String, String> kScreenSpecsJson = {
  'pf1-home': r'''
{"formato":1,"name":"PF1 · Home","form":"phone","blocks":[{"id":"b_1","type":"saldo","props":{"valor":"R$ 2.912,47","entradas":"R$ 300,00","saidas":"R$ 120,00","oculto":false},"bindings":{"valor":"saldoFormatado","entradas":"entradasDoMes","saidas":"saidasDoMes"}},{"id":"b_2","type":"cabecalhoDeSecao","props":{"rotulo":"ATALHOS"}},{"id":"b_3","type":"lista","props":{"titulo":"","idioma":"menu"},"slots":{"itens":[{"id":"b_4","type":"linha","props":{"icone":"pixLight","titulo":"Pix","subtitulo":"Enviar, receber e cobrar"}},{"id":"b_5","type":"linha","props":{"icone":"barcodeLight","titulo":"Pagar","subtitulo":"Boleto, conta e recarga"}},{"id":"b_6","type":"linha","props":{"icone":"arrowRightArrowLeftLight","titulo":"Transferir","subtitulo":"TED e entre contas"}}]}},{"id":"b_7","type":"cabecalhoDeSecao","props":{"rotulo":"PRECISA DE VOCÊ"}},{"id":"b_8","type":"lista","props":{"titulo":"","idioma":"carded"},"slots":{"itens":[{"id":"b_9","type":"linha","props":{"icone":"clockLight","titulo":"Autorização pendente","subtitulo":"Vence em 2 dias"}}]}},{"id":"b_10","type":"cartaoDeDestaque","props":{"icone":"piggyBankLight","titulo":"Conta PJ","descricao":"Alçadas, operadores e aprovação em duas mãos.","acao":"Conhecer"}}],"top":[{"id":"b_11","type":"cabecalhoDaHome","props":{"nome":"Ana","conta":"Conta PF"},"bindings":{"nome":"nomeDoTitular","conta":"rotuloDaConta"}}],"bottom":[{"id":"b_12","type":"barraDeBaixo","props":{"label":"Continuar","labelSecundario":""}}],"scrollableContent":true,"notes":[{"kind":"decisao","text":"O saldo, o nome e o rótulo da conta são BINDING e não texto. Placeholder escrito à mão vira mock silencioso — o dev copia o código e leva o valor fixo pro app."},{"kind":"regra","text":"O ritmo é o contentGap (s5). Nenhum bloco de espaçamento na tela: 23% dos blocos das 99 telas do primeiro filho eram só espaço, e é a medição que gerou a regra."},{"kind":"borda","text":"Saldo oculto: a prop `oculto` troca o valor por pontos e o leitor de tela anuncia \"saldo oculto\". Sem estado próprio de tela — é a mesma HOME."},{"kind":"a11y","text":"O rótulo do botão primário deste DS está em 3,46:1 (abaixo de AA), e o pedido do papel `primary` está aberto com o pai. Esta tela não tem botão primário por isso."}],"contentGap":"s5"}
''',
  'pf2-pix-valor': r'''
{"formato":1,"name":"PF2 · Pix · valor","form":"phone","blocks":[{"id":"b_1","type":"texto","props":{"conteudo":"Transferir para","preset":"bodySm"}},{"id":"b_2","type":"texto","props":{"conteudo":"Texto de apoio.","preset":"titleMd"},"bindings":{"conteudo":"nomeDoDestinatario"}},{"id":"b_3","type":"campo","props":{"rotulo":"Valor","placeholder":"R$ 0,00","ajuda":"O valor sai da sua conta na hora.","erro":"","desabilitado":false}},{"id":"b_4","type":"lista","props":{"titulo":"","idioma":"carded"},"slots":{"itens":[{"id":"b_5","type":"linha","props":{"icone":"walletLight","titulo":"Saldo disponível","subtitulo":"Nome, CPF e contato"},"bindings":{"subtitulo":"saldoFormatado"}}]}}],"top":[{"id":"b_6","type":"cascaDeTopo","props":{"titulo":"","esquerda":"voltar"}}],"bottom":[{"id":"b_7","type":"barraDeBaixo","props":{"label":"Continuar","labelSecundario":""}}],"scrollableContent":true,"notes":[{"kind":"decisao","text":"A barra de topo não tem título: o contexto está no corpo (\"Transferir para <nome>\"), e repetir no topo põe o mesmo texto duas vezes na mesma dobra. É o que o app faz."},{"kind":"borda","text":"Valor acima do saldo: o campo mostra o erro e o CTA desliga. O erro é prop do campo, não bloco novo — estado de validação mora no componente que valida."},{"kind":"a11y","text":"O teclado numérico abre com a tela (autofocus no app). O CTA fica na base fixa, então ele não é coberto pelo teclado — é a razão de o contrato mandar CTA pro `bottom`."}],"contentGap":"s4"}
''',
  'pf3-pix-revisar': r'''
{"formato":1,"name":"PF3 · Pix · revisar","form":"phone","blocks":[{"id":"b_1","type":"valor","props":{"valor":"R$ 1.240,00","rotulo":"Você vai transferir","carimbo":"","heroi":true},"bindings":{"valor":"valorFormatado"}},{"id":"b_2","type":"cabecalhoDeSecao","props":{"rotulo":"PARA"}},{"id":"b_3","type":"lista","props":{"titulo":"","idioma":"carded"},"slots":{"itens":[{"id":"b_4","type":"linha","props":{"icone":"userLight","titulo":"Dados pessoais","subtitulo":"Nome, CPF e contato"},"bindings":{"titulo":"nomeDoDestinatario","subtitulo":"documentoMascarado"}},{"id":"b_5","type":"linha","props":{"icone":"landmarkLight","titulo":"Dados pessoais","subtitulo":"Nome, CPF e contato"},"bindings":{"titulo":"instituicao","subtitulo":"chavePix"}}]}},{"id":"b_6","type":"cabecalhoDeSecao","props":{"rotulo":"DETALHES"}},{"id":"b_7","type":"lista","props":{"titulo":"","idioma":"menu"},"slots":{"itens":[{"id":"b_8","type":"linha","props":{"icone":"noteLightFull","titulo":"Descrição","subtitulo":"Opcional"}},{"id":"b_9","type":"linha","props":{"icone":"calendarDayLight","titulo":"Quando","subtitulo":"Nome, CPF e contato"},"bindings":{"subtitulo":"dataDoEnvio"}}]}}],"top":[{"id":"b_10","type":"cascaDeTopo","props":{"titulo":"","esquerda":"voltar"}}],"bottom":[{"id":"b_11","type":"barraDeBaixo","props":{"label":"Confirmar","labelSecundario":""}}],"scrollableContent":true,"notes":[{"kind":"decisao","text":"Tela só de leitura com UM CTA. O que dá pra mudar aqui volta pra tela anterior — editar no lugar em que se confirma é como se confirma sem ler."},{"kind":"regra","text":"No app o fundo é BoldBackdrop.solido, e no board é o mood do produto: o fundo do frame é gancho do catálogo (um por produto), não campo da spec."},{"kind":"a11y","text":"O valor é o heroi da tela e o leitor de tela o anuncia primeiro. Confirmar sem ouvir o valor é o defeito que a hierarquia evita."}],"contentGap":"s4"}
''',
  'pf4-pix-enviado': r'''
{"formato":1,"name":"PF4 · Pix · enviado","form":"phone","blocks":[{"id":"b_1","type":"resumoDaTransacao","props":{"titulo":"Pix enviado","valor":"R$ 120,00","quando":"30 de julho · 14:32","estado":"concluida"},"bindings":{"valor":"valorFormatado","quando":"dataDoEnvio"}},{"id":"b_2","type":"cabecalhoDeSecao","props":{"rotulo":"PARA"}},{"id":"b_3","type":"lista","props":{"titulo":"","idioma":"carded"},"slots":{"itens":[{"id":"b_4","type":"linha","props":{"icone":"userLight","titulo":"Dados pessoais","subtitulo":"Nome, CPF e contato"},"bindings":{"titulo":"nomeDoDestinatario","subtitulo":"documentoMascarado"}}]}},{"id":"b_5","type":"cabecalhoDeSecao","props":{"rotulo":"DETALHES"}},{"id":"b_6","type":"lista","props":{"titulo":"","idioma":"menu"},"slots":{"itens":[{"id":"b_7","type":"linha","props":{"icone":"hashtagLockLight","titulo":"ID da transação","subtitulo":"Nome, CPF e contato"},"bindings":{"subtitulo":"idDaTransacao"}},{"id":"b_8","type":"linha","props":{"icone":"noteLightFull","titulo":"Descrição","subtitulo":"—"}}]}}],"top":[{"id":"b_9","type":"cascaDeTopo","props":{"titulo":"","esquerda":"fechar"}}],"bottom":[{"id":"b_10","type":"barraDeBaixo","props":{"label":"Compartilhar comprovante","labelSecundario":"Voltar ao início"}}],"scrollableContent":true,"notes":[{"kind":"decisao","text":"O fecho é `fechar` e não `voltar`: o fluxo terminou, e voltar pra revisão de um Pix já enviado é oferecer uma ação que não existe mais."},{"kind":"regra","text":"O ID da transação é o dado que o suporte pede. Ele fica em DETALHES e não escondido atrás de um toque — comprovante que esconde o identificador não serve pro que existe."},{"kind":"borda","text":"Sem descrição, a linha mostra \"—\" e não some: linha que desaparece muda a altura do comprovante entre dois envios e faz a pessoa procurar o que não foi preenchido."}],"contentGap":"s4"}
''',
  'pj1-autorizacoes': r'''
{"formato":1,"name":"PJ1 · Autorizações","form":"phone","blocks":[{"id":"b_1","type":"valor","props":{"valor":"R$ 1.240,00","rotulo":"Saldo disponível","carimbo":"","heroi":false},"bindings":{"valor":"valorDoPedido","rotulo":"nomeDoSolicitante","carimbo":"criadoEm"}},{"id":"b_2","type":"progressoDeAprovacao","props":{"colhidas":"1","exigidas":"2","exigeMaster":true,"compacto":false},"bindings":{"colhidas":"assinaturasColhidas","exigidas":"assinaturasExigidas"}},{"id":"b_3","type":"prazoDaPendencia","props":{"horas":"3","idade":""},"bindings":{"idade":"idadeDaPendencia"}},{"id":"b_4","type":"cabecalhoDeSecao","props":{"rotulo":"A ALÇADA DESTA CONTA"}},{"id":"b_5","type":"escadaDeAlcadas","props":{"degraus":"R$ 5.000,00 | 0\n| 2 master","densa":true}}],"top":[{"id":"b_6","type":"cascaDeTopo","props":{"titulo":"Autorizações","esquerda":"voltar"}},{"id":"b_7","type":"abas","props":{"abas":"Pendentes, Histórico, Minhas","selecionada":"0"}}],"bottom":[{"id":"b_8","type":"barraDeBaixo","props":{"label":"Aprovar","labelSecundario":"Rejeitar"}}],"scrollableContent":true,"notes":[{"kind":"decisao","text":"Os dois botões moram DENTRO da barra de baixo, como primário e secundário dela — CTA solto no rodapé não existe neste produto. No app estes dois são uma linha dentro do cartão do pedido, e não o rodapé da tela; a barra é a forma que o vocabulário tem."},{"kind":"regra","text":"O destrutivo é o ESTADO `error` sobre o tipo secundário, e não um tipo próprio. É a medição que o botão ganhou: 16 sítios de destrutivo no app, nenhum deles um tipo."},{"kind":"borda","text":"Sem `expiresAt` no contrato do backend, o prazo mostra a IDADE da pendência em vez de inventar contagem regressiva. É a decisão que o app já tomou, e ela vem junto."},{"kind":"a11y","text":"O progresso anuncia a frase inteira (\"1 de 2 assinaturas, exige master\") em vez de dois números soltos, e a escada usa `onPrimarySubtle`/`onSuccessSubtle` — o par que passa em AA."}],"contentGap":"s4"}
''',
};
