// GERADO — não editar à mão.
//
// Fonte: `app-newbold`, `dart run tool/inventario_de_adocao.dart`.
// Não se corrige um gerado, se roda o gerador.
// O import é o MOTOR e não o contrato: o catálogo declara um pai só, porque o motor
// reexporta o contrato — declarar os dois dá conflito de resolução (o `path:` interno
// do monorepo do pai resolve como commit, e o pub trata tag e commit como descrições
// diferentes).
import 'package:diletta_catalog_core/diletta_catalog_core.dart';

/// A adoção do DS no app do Conta BOLD, medida no código do app.
const inventarioDoBold = InventarioDeAdocao(
  unidade: 'arquivos',
  medidoPor: 'dart run tool/inventario_de_adocao.dart (app-newbold) · '
      'confere em flutter test test/a_adocao_do_ds_tem_numero_test.dart',
  pecas: [
  PecaNaAdocao(nome: 'BoldAlert', alcance: 21, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldAvatar', alcance: 4, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldBottomApp', alcance: 45, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldButton', alcance: 50, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldCard', alcance: 36, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldDatePicker', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldDialog', alcance: 14, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldEmptyState', alcance: 7, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldIcon', alcance: 39, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldListGroup', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldListTile', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldPermissionGroup', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldPermissionItem', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldReceipt', alcance: 5, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldReceiptRow', alcance: 5, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldReceiptSection', alcance: 5, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSearchInput', alcance: 6, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSecondaryBackground', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSectionHeader', alcance: 38, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSeeAllLink', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSheet', alcance: 27, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSpotIcon', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldStatusTag', alcance: 6, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSummaryAction', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSummaryRow', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSummarySection', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldTabItem', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldToast', alcance: 79, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldTopBar', alcance: 87, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldTransactionSummary', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaActionDirection', alcance: 16, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAmount', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAppList', alcance: 47, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAppListRow', alcance: 50, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAvatar', alcance: 4, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaCheckbox', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaExpansionTile', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIconButton', alcance: 10, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIconButtonSize', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIconButtonType', alcance: 23, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIconFlush', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaLeftAccessory', alcance: 44, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaMiddleAccessory', alcance: 46, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaNavRightIcon', alcance: 15, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaNavigationLeftAccessory', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaNavigationRightAccessory', alcance: 16, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaPageTitle', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaRadioList', alcance: 5, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaRadioOption', alcance: 5, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaRightAccessory', alcance: 32, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaShimmer', alcance: 12, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSkeleton', alcance: 12, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSpotIcon', alcance: 21, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSpotState', alcance: 44, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSpotType', alcance: 54, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaStatusTag', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaStatusTone', alcance: 14, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaTheme', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaThemeScope', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaToggleSwitch', alcance: 9, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldAppListDayGroup', alcance: 1, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldAvatarRow', alcance: 3, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldBusy', alcance: 5, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldCurrencyField', alcance: 6, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldFilterChip', alcance: 4, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldIllustration', alcance: 5, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldKeypad', alcance: 1, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldLogo', alcance: 5, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldMenuTile', alcance: 4, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldNavAction', alcance: 42, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldNavigationButton', alcance: 2, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldNoticeRow', alcance: 2, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldOperatingContext', alcance: 1, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldOperatingSlot', alcance: 2, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldOperatingStrip', alcance: 1, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldPinDots', alcance: 1, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldPixMark', alcance: 1, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldPromoCard', alcance: 2, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldSelectField', alcance: 3, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldStatusBadge', alcance: 3, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldTextField', alcance: 42, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldSeloQuantico', alcance: 11, estado: EstadoDaAdocao.deliberado, razao: 'narrativa de marca: o selo do par quântico é o que este produto tem e nenhum outro. Veredito do dono em 2026-07-29, junto com a decisão oposta pros outros exclusivos, que subiram pra linguagem'),
  PecaNaAdocao(nome: 'BoldQuantumPairingScreen', alcance: 1, estado: EstadoDaAdocao.deliberado, razao: 'mesma decisão do selo: pareamento quântico é história da marca, não vocabulário de interface'),
  PecaNaAdocao(nome: 'AppButton', alcance: 18, estado: EstadoDaAdocao.lacuna, temParNoDs: true),
  PecaNaAdocao(nome: 'AppColors', alcance: 47, estado: EstadoDaAdocao.lacuna, temParNoDs: true),
  PecaNaAdocao(nome: 'AppCurrencyField', alcance: 1, estado: EstadoDaAdocao.lacuna, temParNoDs: true),
  PecaNaAdocao(nome: 'AppGradients', alcance: 7, estado: EstadoDaAdocao.lacuna, temParNoDs: true),
  PecaNaAdocao(nome: 'AppRadius', alcance: 30, estado: EstadoDaAdocao.lacuna, temParNoDs: true),
  PecaNaAdocao(nome: 'AppShadows', alcance: 12, estado: EstadoDaAdocao.lacuna, temParNoDs: true),
  PecaNaAdocao(nome: 'AppSpacing', alcance: 38, estado: EstadoDaAdocao.lacuna, temParNoDs: true),
  PecaNaAdocao(nome: 'AppTextStyles', alcance: 42, estado: EstadoDaAdocao.lacuna, temParNoDs: true),
  PecaNaAdocao(nome: 'AtmosphericBackground', alcance: 4, estado: EstadoDaAdocao.lacuna, temParNoDs: true),
  PecaNaAdocao(nome: 'appIcon', alcance: 30, estado: EstadoDaAdocao.lacuna, temParNoDs: true),
  ],
);
