// GERADO — não editar à mão.
//
// Fonte: `app-newbold`, `dart run tool/inventario_de_adocao.dart`.
// Não se corrige um gerado, se roda o gerador.
// O import é o MOTOR e não o contrato: o catálogo declara um pai só, porque o motor
// reexporta o contrato — declarar os dois dá conflito de resolução (o `path:` interno
// do monorepo do pai resolve como commit, e o pub trata tag e commit como descrições
// diferentes).
import 'package:diletta_catalog_core/diletta_catalog_core.dart';

/// A adoção do DS no app do Conta BOLD, medida no código do app.
const inventarioDoBold = InventarioDeAdocao(
  unidade: 'arquivos',
  medidoPor: 'dart run tool/inventario_de_adocao.dart (app-newbold) · '
      'confere em flutter test test/a_adocao_do_ds_tem_numero_test.dart',
  pecas: [
  PecaNaAdocao(nome: 'BoldAlert', alcance: 20, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldAvatar', alcance: 4, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldAvatarRow', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldBottomApp', alcance: 43, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldButton', alcance: 61, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldCard', alcance: 32, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldCurrencyField', alcance: 6, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldDatePicker', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldDialog', alcance: 13, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldEmptyState', alcance: 6, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldIcon', alcance: 75, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldNavAction', alcance: 41, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldNavigationButton', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldPermissionGroup', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldPermissionItem', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldReceipt', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldReceiptRow', alcance: 8, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldReceiptSection', alcance: 8, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSearchInput', alcance: 6, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSecondaryBackground', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSectionHeader', alcance: 38, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSeeAllLink', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSheet', alcance: 22, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldStatusTag', alcance: 6, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSummaryAction', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSummaryRow', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSummarySection', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldTabItem', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldTextField', alcance: 40, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldToast', alcance: 75, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldTopBar', alcance: 83, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldTransactionSummary', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaActionDirection', alcance: 16, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAmount', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAppList', alcance: 47, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAppListRow', alcance: 50, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAvatar', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaCheckbox', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaDivider', alcance: 5, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaDropdown', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaExpansionTile', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIconButton', alcance: 9, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIconButtonSize', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIconButtonType', alcance: 23, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIconFlush', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaLeftAccessory', alcance: 44, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaMiddleAccessory', alcance: 46, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaNavRightIcon', alcance: 15, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaNavigationLeftAccessory', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaNavigationRightAccessory', alcance: 16, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaPageTitle', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaRadioList', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaRadioOption', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaRadius', alcance: 12, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaRightAccessory', alcance: 32, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaShimmer', alcance: 12, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSkeleton', alcance: 12, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSpotIcon', alcance: 25, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSpotState', alcance: 48, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSpotType', alcance: 53, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaStatusTag', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaStatusTone', alcance: 16, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaThemeScope', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaToggleSwitch', alcance: 7, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldAppListDayGroup', alcance: 1, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldFilterChip', alcance: 3, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldMenuTile', alcance: 4, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldNoticeRow', alcance: 2, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldPromoCard', alcance: 2, estado: EstadoDaAdocao.lacuna),
  PecaNaAdocao(nome: 'BoldSeloQuantico', alcance: 11, estado: EstadoDaAdocao.deliberado, razao: 'narrativa de marca: o selo do par quântico é o que este produto tem e nenhum outro. Veredito do dono em 2026-07-29, junto com a decisão oposta pros outros exclusivos, que subiram pra linguagem'),
  PecaNaAdocao(nome: 'BoldQuantumPairingScreen', alcance: 1, estado: EstadoDaAdocao.deliberado, razao: 'mesma decisão do selo: pareamento quântico é história da marca, não vocabulário de interface'),
  PecaNaAdocao(nome: 'BoldBusy', alcance: 5, estado: EstadoDaAdocao.deliberado, razao: 'não é desenho, é COMPORTAMENTO: trava o formulário inteiro enquanto a ação está em voo, pra a pessoa não editar depois de mandar. O pai tem spinner (DilettaLoadingSpinner); o que falta lá não é peça, é a regra de quem pode digitar'),
  PecaNaAdocao(nome: 'BoldLogo', alcance: 5, estado: EstadoDaAdocao.deliberado, razao: 'a marca do Conta BOLD. O pai tem DilettaLogo, que é a marca DELE — duas marcas, não duas versões da mesma'),
  PecaNaAdocao(nome: 'BoldIllustration', alcance: 5, estado: EstadoDaAdocao.deliberado, razao: 'o kit de ilustração deste produto. O pai tem DilettaIllustration com o kit dele, e ilustração é arte, não vocabulário: as duas peças fazem a mesma coisa com acervos diferentes'),
  PecaNaAdocao(nome: 'BoldPixMark', alcance: 1, estado: EstadoDaAdocao.deliberado, razao: 'o símbolo oficial do Pix, que é marca de terceiro (BACEN) e não pertence a nenhum dos dois DS'),
  PecaNaAdocao(nome: 'BoldOperatingContext', alcance: 1, estado: EstadoDaAdocao.deliberado, razao: 'não é peça: é um InheritedWidget que declara, uma vez no topo, que a pessoa age em nome de outra conta. Escopo de estado não sobe pra linguagem — o pai não tem como saber quem opera o quê'),
  PecaNaAdocao(nome: 'BoldOperatingStrip', alcance: 1, estado: EstadoDaAdocao.deliberado, razao: 'a faixa de "operando como", e o que ela desenha é uma regra deste produto: PJ com operador agindo em nome da conta. O par no pai seria um banner genérico, e o que importa aqui é a REGRA, não a faixa'),
  PecaNaAdocao(nome: 'AppColors', alcance: 1, estado: EstadoDaAdocao.lacuna, temParNoDs: true),
  PecaNaAdocao(nome: 'Letti (app à parte)', alcance: 3, estado: EstadoDaAdocao.deliberado, razao: 'app à parte que mora neste repo — não é tela do Conta BOLD e não se refaz nesta adoção (dono, 2026-08-08)'),
  ],
);
