// GERADO — não editar à mão.
//
// Fonte: `app-newbold`, `dart run tool/inventario_de_adocao.dart`.
// Não se corrige um gerado, se roda o gerador.
// O import é o MOTOR e não o contrato: o catálogo declara um pai só, porque o motor
// reexporta o contrato — declarar os dois dá conflito de resolução (o `path:` interno
// do monorepo do pai resolve como commit, e o pub trata tag e commit como descrições
// diferentes).
import 'package:diletta_catalog_core/diletta_catalog_core.dart';

/// A adoção do DS no app do Conta BOLD, medida no código do app.
const inventarioDoBold = InventarioDeAdocao(
  unidade: 'arquivos',
  medidoPor: 'dart run tool/inventario_de_adocao.dart (app-newbold) · '
      'confere em flutter test test/a_adocao_do_ds_tem_numero_test.dart',
  pecas: [
  PecaNaAdocao(nome: 'DilettaAbsoluteColors', alcance: 117, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaActionDirection', alcance: 19, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAmount', alcance: 6, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAppList', alcance: 53, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAppListDayGroup', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAppListRow', alcance: 59, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaAvatar', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaBadge', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaCalendar', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaCheckbox', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaDetailEnfase', alcance: 4, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaDetailPorte', alcance: 4, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaDetailRow', alcance: 8, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaDialog', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaDivider', alcance: 10, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaDropdown', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaEmptyState', alcance: 25, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaExpansionTile', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaFrame', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIconButton', alcance: 8, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIconButtonSize', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIconButtonType', alcance: 24, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIconFlush', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaIllustration', alcance: 18, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaInlineAlert', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaLeftAccessory', alcance: 50, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaLoadingSpinner', alcance: 40, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaLogo', alcance: 5, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaMiddleAccessory', alcance: 52, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaMotion', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaNavRightIcon', alcance: 18, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaNavigationLeftAccessory', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaNavigationRightAccessory', alcance: 19, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaOtpInput', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaPageTitle', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaProgressBar', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaProgressTone', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaRadioList', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaRadioMark', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaRadioOption', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaRadius', alcance: 4, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaReceiptRow', alcance: 8, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaReceiptSection', alcance: 8, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaRightAccessory', alcance: 40, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSectionHeader', alcance: 44, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSeeAllLink', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaShimmer', alcance: 16, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSkeleton', alcance: 16, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSpacing', alcance: 180, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSpinnerSize', alcance: 32, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSpotForma', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSpotIcon', alcance: 27, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSpotState', alcance: 56, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaSpotType', alcance: 53, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaStatusTag', alcance: 3, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaStatusTagPorte', alcance: 4, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaStatusTone', alcance: 23, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaTextLinkTone', alcance: 2, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaThemeScope', alcance: 1, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'DilettaToggleSwitch', alcance: 9, estado: EstadoDaAdocao.adotado),
  PecaNaAdocao(nome: 'BoldSeloQuantico', alcance: 14, estado: EstadoDaAdocao.deliberado, razao: 'narrativa de marca: o selo do par quântico é o que este produto tem e nenhum outro. Veredito do dono em 2026-07-29, junto com a decisão oposta pros outros exclusivos, que subiram pra linguagem'),
  PecaNaAdocao(nome: 'AppColors', alcance: 1, estado: EstadoDaAdocao.lacuna, temParNoDs: true),
  PecaNaAdocao(nome: 'Letti (app à parte)', alcance: 2, estado: EstadoDaAdocao.deliberado, razao: 'app à parte que mora neste repo — não é tela do Conta BOLD e não se refaz nesta adoção (dono, 2026-08-08)'),
  ],
);
